angular.module('spliced.home', [])

.controller('HomeController', function ($scope, Draw, $location) {

  // Create a game! The callback function has the code that is generated by the server, and updates
  // the user's location to a path with the new game code!
  $scope.createGame = function() {
    Draw.createGame(function(code) {
      console.log(code);
      $location.path('/game/' + code);
    });
  }

  // When a user enters the game code into the form field, they'll get forwarded to the ready screen
  // which allows them to opt in to a drawing.
  $scope.enterCode = function(gameCode) {
    var newUrl = '/game/' + gameCode.toLowerCase();
    $location.path(newUrl);
  }

})